### PR TITLE
Bumps fnsv/bootstrap to v2.0.0 and storybook/vue to v6.3.2

### PR DESCRIPTION
**Pull request by xezian**
Bumped this to v2 since it's not really using that much bootstrap anyway. Only updates needed were to utility class [`mr` --> `me`](https://getbootstrap.com/docs/5.0/migration/#utilities)

### CODE REVIEW

**Comment by brxck** [comment]
Weird, why's CI failing?

**Comment by xezian** [comment]
> Weird, why's CI failing?

`Unable to authenticate, need: Basic realm="GitHub Package Registry"`

**Comment by brxck** [comment]
Yes *but why* 😅

**Comment by xezian** [comment]
Looks right to me... :/
```
- run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GPR_READ_TOKEN }}
```

**Comment by xezian** [comment]
Could it be because this is not (no longer?) a private repo? And the secret needs to be scoped to public repos as well? https://stackoverflow.com/a/66876706/8524758

**Comment by brxck** [comment]
Ah, that's gotta be it.

**Comment by xezian** [comment]
Safe to scope the `GPR_READ_TOKEN` to all repos?

**Comment by brxck** [comment]
Maybe bootstrap should just be a peer dependency instead?

**Comment by xezian** [comment]
> Maybe bootstrap should just be a peer dependency instead?

Not entirely sure how peer dependencies work, but removing it from `"devDependencies"` breaks the build for storybook.

`/home/jleo/Documents/Apps/ag-grid-utils/node_modules/@uarizona-fnsv/bootstrap/dist/bootstrap.css doesn't exist`

**Comment by xezian** [comment]
Looking into peer dependencies now, I guess this would be expected. I think it kindof has to be in `"devDependencies"` as well for storybook to work.

**Comment by brxck** [comment]
Ah okay that makes sense yeah. I think it's okay to scope that token to public repos. This repo also doesn't need to be public if it's causing trouble 🤷 we're not even using it at the moment!

**Comment by xezian** [comment]
Scoped the `GPR_READ_TOKEN` to all repositories (in the org). Rerunning ci

**Comment by xezian** [comment]
> Weird, why's CI failing?

**Comment by brxck** [comment]
> npm ERR! missing script: storybook

looks like it changed to `npm run sb` sometime?

**Comment by xezian** [comment]
Ugh I can't seem to get storybook back to version 6.1.20

**Comment by xezian** [comment]
- Deleted `node_modules` and `package-lock.json`
- Ran `npm install`
- Ran `npm run sb` ----> `info @storybook/vue v6.3.3` :confounded:

**Comment by brxck** [comment]
A fresh clone and `npm ci` works fine:

```
❯ npm ls | grep 'storybook'
├── @storybook/addon-actions@6.1.20
├── @storybook/addon-essentials@6.1.20
├── @storybook/addon-links@6.1.20
├── @storybook/vue@6.1.20
├── cypress-storybook@0.5.0
```

Reset your branch and try again without touching storybook?

**Comment by xezian** [comment]
> Reset your branch and try again without touching storybook?

Still getting `info @storybook/vue v6.3.3` ??? 

Also happens in CI! where is the hidden version pin?

**Comment by brxck** [comment]
Try this:

```
❯ git checkout main package-lock.json
Updated 1 path from ef7877d
❯ npm i

changed 1 package, and audited 2151 packages in 6s

43 vulnerabilities (21 moderate, 22 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
❯ npm ls | grep 'storybook'
├── @storybook/addon-actions@6.1.20
├── @storybook/addon-essentials@6.1.20
├── @storybook/addon-links@6.1.20
├── @storybook/vue@6.1.20
├── cypress-storybook@0.5.0
```

**Comment by xezian** [comment]
Awesome, also still weird, but I think that did it.

**Comment by xezian** [comment]
Ok... at this point I'm going to just see if I can get the tests passing again, as I've got the same results as CI locally with `npm run cy:run -- --headless --browser firefox`

**Comment by xezian** [comment]
Actually I'm going to try recreating this on a new branch but not ever upgrading storybook...

**Comment by xezian** [comment]
Wondering how these tests have ever passed at all!

**Comment by xezian** [comment]
I am at a loss with the cypress tests Created a new branch and did not upgrade anything, and these  tests are still failing. I'm really not sure if they ever passed at all, as the last version that had successful tests run in CI doesn't even seem to include cypress-storybook​​​​​​​ commands. Putting this down for awhile because it isn't making any sense lol

**Comment by brxck** [comment]
It's totally possible. I rather unceremoniously dropped this project when I found out it wasn't going to be needed any time soon.

**Pull request merged**
